// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sword.EntityFrameworkCore;

#nullable disable

namespace Sword.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(SwordDbContext))]
    [Migration("20220316085205_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sword.Domain.Resc", b =>
                {
                    b.Property<Guid>("RescId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Deletor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Updator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RescId");

                    b.HasIndex("Identity")
                        .IsUnique();

                    b.ToTable("Resc");

                    b.HasData(
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d00"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "System",
                            Icon = "form",
                            Identity = "System",
                            Type = 0,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d01"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Resc",
                            Icon = "form",
                            Identity = "Resc",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d00"),
                            Type = 0,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d02"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Create",
                            Icon = "form",
                            Identity = "Resc.Create",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d01"),
                            Type = 1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d03"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Update",
                            Icon = "form",
                            Identity = "Resc.Update",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d01"),
                            Type = 1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d04"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Delete",
                            Icon = "form",
                            Identity = "Resc.Delete",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d01"),
                            Type = 1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d05"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Role",
                            Icon = "form",
                            Identity = "Role",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d00"),
                            Type = 0,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d06"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Create",
                            Icon = "form",
                            Identity = "Role.Create",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d05"),
                            Type = 1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d07"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Update",
                            Icon = "form",
                            Identity = "Role.Update",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d05"),
                            Type = 1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d08"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Delete",
                            Icon = "form",
                            Identity = "Role.Delete",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d05"),
                            Type = 1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d09"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "User",
                            Icon = "form",
                            Identity = "User",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d00"),
                            Type = 0,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d10"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Create",
                            Icon = "form",
                            Identity = "User.Create",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d09"),
                            Type = 1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d11"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Update",
                            Icon = "form",
                            Identity = "User.Update",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d09"),
                            Type = 1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            RescId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d12"),
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "Delete",
                            Icon = "form",
                            Identity = "User.Delete",
                            ParentId = new Guid("890d6a3c-6a7f-4277-8e24-e14168f61d09"),
                            Type = 1,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Sword.Domain.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Deletor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Updator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("RoleId");

                    b.HasIndex("Display")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Sword.Domain.RoleResc", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RescId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "RescId");

                    b.ToTable("RoleResc");
                });

            modelBuilder.Entity("Sword.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeleteTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Deletor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenExpireTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenRefreshExpireTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Updator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("UserId");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Account = "tester",
                            Available = true,
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            DeleteTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deletor = new Guid("00000000-0000-0000-0000-000000000000"),
                            Display = "tester",
                            Password = "tester",
                            Type = 0,
                            UpdateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Sword.Domain.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
